# Default values for kubetoy.
replicaCount: 3
image:
  repository: registry.ng.bluemix.net/kubetoy/kubetoy
  pullPolicy: IfNotPresent
service:
  name: kubetoy-service
  type: NodePort
  externalPort: 80
storage:
  useSharedStorage: true
  pvc: kubetoy-pvc
  accessmode: ReadWriteMany
